version: "3.8"

services:
  server:
    image: node:18-alpine
    container_name: area-server
    command: sh -c "echo 'Installing...'; npm install --no-optional --no-audit --no-fund --omit=optional; npm run dev"
    ports:
      - '8080:8080'
      - '9229:9229'
    working_dir: /app
    volumes:
      - ./server/:/app
    env_file:
      - "database.env"
      - "tokens.env"
    depends_on:
      - mysql
    networks:
      - phil

  mysql:
    image: mysql:5.7
    container_name: area-mysql
    volumes:
      - todo-mysql-data:/var/lib/mysql
    env_file: "database.env"
    ports:
      - "6033:3306"
    networks:
      - phil
      
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: area-pma
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    ports:
      - '6969:80'
    depends_on:
      - mysql
    networks:
      - phil

  # androidapp:
  #   build: ./MyArea
  #   tty: true
  #   volumes:
  #     - android-apk:/result

  web:
    image: node:18-alpine
    container_name: area-web
    working_dir: /app
    command: sh -c "npm install; npm run start"
    volumes:
      - ./web/:/app
      - android-apk:/result
    ports:
      - 8081:8081

volumes:
  todo-mysql-data:
  android-apk:

networks:
  phil:
    driver: bridge