version: "3.8"

services:
  server:
    container_name: area-server
    build: ./server
    ports:
      - '8080:8080'
      - '9229:9229'
    env_file:
      - "database.env"
      - "tokens.env"
    depends_on:
      - mysql
    networks:
      - phil

  mysql:
    image: mysql:5.7
    container_name: area-mysql
    volumes:
      - todo-mysql-data:/var/lib/mysql
    env_file: "database.env"
    ports:
      - "6033:3306"
    networks:
      - phil
      
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: area-pma
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    ports:
      - '6969:80'
    depends_on:
      - mysql
    networks:
      - phil

  androidapp:
    container_name: android-app
    build: ./MyArea
    volumes:
      - android-apk:/result/

  web:
    container_name: area-web
    build: ./web
    volumes:
      - android-apk:/result/
    ports:
      - 8081:8081

volumes:
  todo-mysql-data:
  android-apk:

networks:
  phil:
    driver: bridge