version: "3.8"

services:
  app:
    image: node:18-alpine
    #command: npm start
    stdin_open: true # docker run -i
    #tty: true        # docker run -t
    ports:
      - 3000:3000
    working_dir: /app
    volumes:
      - ./server/:/app
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
      MYSQL_DB: todos
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    volumes:
      - todo-mysql-data:/var/lib/mysql
    environment: 
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: todos

volumes:
  todo-mysql-data: