version: "3.8"

services:
  server:
    image: node:18-alpine
    container_name: area-server
    command: sh -c "npm install; npm run dev"
    ports:
      - 8080:8080
      - 9229:9229
    working_dir: /app
    volumes:
      - ./server/:/app
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
      MYSQL_DB: area
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    container_name: area-mysql
    volumes:
      - todo-mysql-data:/var/lib/mysql
    environment: 
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: area
    ports:
      - "6033:3306"
      
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: area-pma
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    ports:
      - 8081:80
    depends_on:
      - mysql

volumes:
  todo-mysql-data: